"""empty message

Revision ID: 82c9df11a354
Revises: 5f987d26a3d6
Create Date: 2021-06-21 23:11:03.103943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c9df11a354'
down_revision = '5f987d26a3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingcarts',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('cant', sa.Integer(), nullable=True),
    sa.Column('unitprice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_user', 'id_pet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcarts')
    # ### end Alembic commands ###
